const blogsData = [
  {
    blogId: '183fc7bc-9845-4631-84aa-46a68cce72d2',
    title: 'Tech Ethics: Navigating the Moral Dilemmas of Innovation',
    body: 'As technology advances, ethical considerations become increasingly important. This blog will delve into the ethical challenges posed by emerging technologies such as AI, biotechnology, and surveillance. It will also discuss the role of individuals, organizations, and governments in addressing these ethical dilemmas.',
    authorId: 'f11a211e-0101-45c8-bc71-18d31e30685e',
    createdAt: '2023-10-10 02:42:07',
    updatedAt: '2023-10-10 02:42:07',
  },
  {
    blogId: '1cb99a60-80f1-48c7-bc87-e97db5545397',
    title: 'Again title',
    body: 'Hello this is title',
    authorId: '3a7ac5c7-706e-4ad2-aa2f-bde4f1820ae2',
    createdAt: '2023-10-10 09:37:52',
    updatedAt: '2023-10-10 09:37:52',
  },
  {
    blogId: '26e49dd3-98ce-40d3-8c22-c103eb9dcc57',
    title:
      'The Green Tech Revolution: Sustainable Innovations for a Greener Future',
    body: 'Sustainability is a growing concern in the tech industry. This blog will highlight sustainable innovations, including renewable energy solutions, eco-friendly gadgets, and green data centers. It will discuss how these technologies are driving a more environmentally friendly future.',
    authorId: 'f11a211e-0101-45c8-bc71-18d31e30685e',
    createdAt: '2023-10-10 02:42:35',
    updatedAt: '2023-10-10 02:42:35',
  },
  {
    blogId: '3392f72e-e7c7-475f-bd16-0081db7fda6c',
    title: 'Signal object test',
    body: 'This is the test',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 09:26:33',
    updatedAt: '2023-10-18 09:26:33',
  },
  {
    blogId: '6b1e54f1-5ddc-42fc-ae0a-04af918bc65b',
    title: 'Long text',
    body: '\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce suscipit id tortor nec faucibus. Etiam a auctor augue, non pharetra augue. Sed nisi felis, dictum nec est maximus, hendrerit placerat erat. Aliquam dapibus sapien lectus, sit amet feugiat purus sodales quis. Duis vestibulum magna nunc, ultricies euismod metus gravida at. Vestibulum elementum ex quis tristique feugiat. Suspendisse auctor, ex sit amet sollicitudin ultrices, magna tellus efficitur libero, sit amet mollis magna diam vitae justo. Vestibulum ac odio bibendum, molestie sapien vel, accumsan nibh. Maecenas blandit nulla magna, eget vestibulum diam interdum at. Suspendisse sed sagittis tortor. Morbi sed mattis nunc. Cras convallis, tortor in mattis tempor, justo massa varius justo, vel venenatis sapien eros sit amet turpis. Fusce aliquet condimentum orci, vitae iaculis eros finibus eu. Donec luctus tincidunt turpis, quis sagittis erat porta ut. Curabitur nec pulvinar felis. Nullam sed vestibulum nibh.\n\nPhasellus pulvinar hendrerit mollis. Phasellus condimentum neque nec dui tempor, a ornare erat varius. Etiam orci turpis, tincidunt a sapien ac, lobortis lobortis ante. Sed sodales, tellus ultrices viverra mattis, augue purus sodales risus, eget facilisis ligula libero ac neque. Aenean mollis quam at tellus faucibus feugiat. Vivamus eu laoreet sem. Etiam ultrices sed risus ut consectetur.\n\nPraesent id turpis rhoncus, placerat erat in, iaculis lectus. Suspendisse lectus enim, ultricies at risus eu, condimentum facilisis mauris. Sed dapibus aliquet quam, quis rhoncus augue fringilla nec. Vivamus porttitor urna sed nibh lacinia, ut consectetur lorem vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu vehicula dui. Sed in ultrices ante. Donec eget sem at diam elementum porta. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ac lectus et mauris ullamcorper dignissim pretium placerat magna.\n\nQuisque dapibus feugiat erat, sed fermentum mauris convallis vitae. Sed ultricies est non nunc aliquam efficitur. Nam sapien justo, gravida eu libero at, molestie venenatis tellus. Suspendisse volutpat lacinia mauris, id dictum lorem dapibus hendrerit. Curabitur blandit et lorem tincidunt hendrerit. Donec eget finibus lacus. Pellentesque rutrum risus et nulla mollis, ac posuere enim semper. Quisque blandit eget tortor rutrum elementum. Etiam nec diam in orci euismod egestas eget vel nulla. Vestibulum tincidunt, ipsum nec ornare porta, elit ante pretium enim, eget cursus risus lorem ut enim. Praesent gravida viverra metus vitae egestas. Phasellus et lorem tortor. In et convallis risus. Praesent faucibus metus tortor, pellentesque scelerisque nulla venenatis nec. Aenean quis nisl vitae lorem eleifend pellentesque. Cras tincidunt dictum tellus, a congue justo congue ac.\n\nNam purus ex, venenatis at condimentum quis, vehicula sit amet lacus. Vivamus iaculis congue felis, vel ultricies felis sollicitudin non. In ultrices dignissim egestas. Fusce elementum non nisl et faucibus. Phasellus a pulvinar libero. Phasellus fermentum, sapien eu aliquet accumsan, sapien sem faucibus nibh, ac egestas metus augue sit amet leo. Etiam eros mi, aliquam vel convallis id, fermentum eget mi. Nunc vitae ex arcu. Donec condimentum nisi ac ipsum pellentesque sollicitudin. Nulla facilisi. Fusce ac nisi sed tellus volutpat auctor nec id erat. Morbi cursus arcu lorem, nec elementum nisi volutpat at. Sed feugiat metus sit amet eros dapibus, ultrices aliquam leo facilisis. Aenean ut leo sollicitudin, vulputate augue commodo, sagittis sapien.\n\nProin purus purus, elementum non quam nec, hendrerit faucibus tellus. Aliquam erat volutpat. Sed eu eros metus. Maecenas tincidunt magna quis erat dictum pharetra. Etiam nisi purus, porttitor faucibus augue eget, ultricies rutrum leo. Nunc at pellentesque quam, id egestas ante. Aliquam ac ex ullamcorper, viverra risus vulputate, facilisis risus. Mauris quis ante varius, mattis turpis ut, convallis enim. Quisque quis magna quis lorem mattis posuere in quis arcu. Suspendisse pulvinar felis a quam tempor, nec sollicitudin dolor cursus. Donec a semper magna. Nullam eleifend hendrerit urna, eu condimentum libero. Mauris euismod fermentum sapien, ac consectetur ante blandit vel. In hac habitasse platea dictumst. Vestibulum lacinia eleifend libero in eleifend. Ut nec rutrum eros.\n\nAliquam erat volutpat. Fusce efficitur, eros in tempor aliquam, tortor augue elementum velit, vitae accumsan augue dui at diam. Ut eget elit varius, ultrices metus eget, pharetra est. Nunc eget dignissim velit. Praesent ac mauris neque. Vestibulum non fringilla felis, non tempus elit. Nunc efficitur, libero quis hendrerit ultrices, ipsum turpis interdum ex, eu sagittis odio leo sit amet turpis. Nulla eu dignissim orci. Cras sit amet consequat ex. Ut quis eleifend ligula. Aliquam egestas enim elit, in accumsan velit pulvinar at. Etiam fringilla, nisi ut hendrerit cursus, erat velit facilisis sapien, vitae bibendum libero lorem at nisi. Duis sollicitudin magna in nisl dictum lobortis. Pellentesque egestas enim orci, varius commodo neque tempus at. Donec at massa dolor.\n\nMorbi semper, risus at congue cursus, nisl est vehicula nulla, in tincidunt neque metus nec enim. Mauris sed augue id urna blandit facilisis. Pellentesque nec condimentum risus. Vestibulum suscipit tempus pellentesque. Nam consequat id tellus fermentum tincidunt. Mauris sed metus at odio ullamcorper sollicitudin. Aenean et est gravida, posuere elit vitae, malesuada tellus. Nunc porttitor mattis est dapibus iaculis. Proin sagittis pharetra tellus, sed pretium risus vehicula eu. Praesent suscipit placerat eros, nec eleifend eros facilisis sit amet. Nam tincidunt tempus maximus. Vivamus pretium placerat nisi id dapibus. Donec et odio vel purus convallis dignissim. Sed feugiat metus non nisi tincidunt aliquet. Suspendisse justo ipsum, finibus et mauris vitae, posuere posuere lorem. Aliquam lacinia ullamcorper ex id accumsan.\n\nAenean euismod justo non lorem aliquet, vel sodales magna interdum. Praesent vel leo placerat, scelerisque ligula vitae, auctor arcu. Aenean commodo ligula et blandit laoreet. Nunc varius massa in tellus molestie, ut sodales tellus laoreet. Nulla porttitor viverra accumsan. Etiam vel diam eleifend, fringilla urna a, dapibus eros. Nullam eu augue quis nisi accumsan aliquam id scelerisque velit. Vivamus eu dui malesuada purus placerat aliquam. Integer faucibus lacinia ligula. Mauris varius lacus eu enim vehicula, vitae commodo massa molestie. Donec eget risus mattis, tempor erat vitae, accumsan arcu. Proin fermentum enim quam, at dictum odio rutrum venenatis. Phasellus quis dignissim ex. Sed egestas libero sit amet libero mattis, non porttitor libero ultricies. Maecenas commodo fringilla libero quis hendrerit. Suspendisse eu imperdiet est.\n\nPhasellus ut vehicula felis. Vivamus ultrices non velit in sollicitudin. Vivamus vitae pretium lacus, vel placerat orci. Mauris mattis, tellus a vulputate molestie, tellus turpis imperdiet magna, non mattis libero nisl nec nisi. Nunc nec nulla ut tortor gravida molestie. Proin convallis justo tortor, at vestibulum quam rutrum et. Etiam et sem id nunc sagittis interdum ac vel quam. Proin felis enim, rutrum eget risus ac, faucibus viverra nibh. Nulla iaculis risus ut maximus vestibulum. Donec a cursus velit. Ut in est elit.\n\nUt dapibus ipsum lorem, sed porta odio ornare vel. Fusce a blandit felis. Duis consectetur, justo eu egestas tempor, turpis quam lobortis tortor, nec rutrum metus est eu lorem. Pellentesque commodo turpis metus, maximus aliquam elit aliquet eget. Aliquam interdum lectus mi, sit amet commodo lorem tempor eu. Aliquam pellentesque sem vel vestibulum porttitor. Aenean convallis arcu vitae urna condimentum, sed lobortis nisi tristique. Nunc finibus varius orci. Nunc non nunc maximus, bibendum risus sed, consequat elit. Vivamus vestibulum risus a ornare malesuada. Sed vitae molestie leo.\n\nDonec rhoncus leo a commodo facilisis. In euismod dui et magna ultricies gravida. Praesent suscipit euismod enim a luctus. Maecenas at lectus vel ligula rhoncus mattis. In suscipit mi a magna imperdiet, eu semper ipsum tincidunt. Integer consequat lorem bibendum enim varius congue. Suspendisse sollicitudin lectus sed rutrum euismod. Donec tempus pulvinar enim, eu fringilla nibh pulvinar eget. Sed eu aliquet mi. Sed tempor cursus urna, vitae semper justo bibendum sit amet. Quisque sit amet ultricies sapien. Nam fringilla accumsan arcu, quis semper elit pretium lacinia. Nulla dictum feugiat diam, ac sagittis turpis efficitur ac.\n\nVivamus porttitor dignissim consequat. Phasellus convallis lectus at nisi pharetra, ut cursus erat interdum. Nam vitae eleifend massa, at dictum mi. Quisque ac lectus finibus, fringilla purus pretium, accumsan mi. Proin laoreet in sem a venenatis. Nunc vitae vestibulum urna. Donec id rutrum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ac quam in sapien finibus suscipit. Ut tincidunt mauris et ligula varius, eu euismod metus eleifend. Donec suscipit placerat placerat.\n\nMauris tincidunt bibendum lorem eget condimentum. Duis dapibus sodales elit sed maximus. In fringilla auctor enim at posuere. Sed sit amet bibendum turpis. Quisque at libero non ligula imperdiet bibendum. In mollis iaculis lorem. Sed nunc dolor, dictum eu mattis vitae, posuere sed erat. Quisque ullamcorper lectus laoreet urna faucibus auctor. Suspendisse sed turpis non odio accumsan luctus. Suspendisse potenti. Aenean in velit et libero viverra facilisis id sed enim. Aliquam condimentum laoreet mauris, a vestibulum risus finibus eu. Vivamus et purus ex. Duis vehicula sem elit, elementum blandit augue bibendum sed. Vestibulum tincidunt, sapien vel maximus pulvinar, ligula nibh vulputate tellus, sed iaculis ligula tellus vel risus. Quisque ultricies ullamcorper sapien eget vulputate.\n\nNullam tincidunt convallis aliquet. Aenean maximus congue sem. Sed augue nunc, accumsan eget mi sit amet, vestibulum vehicula augue. Integer commodo nunc eget ante posuere, sit amet efficitur magna aliquam. Sed tincidunt dignissim aliquet. Vivamus egestas at mi nec cursus. Curabitur viverra vulputate ipsum. Fusce sed nunc ante. Vivamus vel convallis sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse commodo et ex dignissim porta. Vivamus in neque suscipit, pretium ipsum vitae, blandit turpis. Suspendisse porta suscipit eros eget dapibus. Nunc ullamcorper in tellus nec eleifend. Proin non libero mauris.\n\nQuisque diam nulla, ultrices vel felis ac, consectetur consectetur dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sed felis ante. Aliquam elit lectus, vulputate sed fringilla sit amet, placerat id urna. Quisque vehicula pellentesque tellus. Mauris eget nulla ornare, dignissim tortor pellentesque, ullamcorper neque. Etiam finibus arcu non nibh pulvinar ultricies. Sed lobortis, augue in pretium gravida, orci dui luctus ex, nec maximus lectus urna sed odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris iaculis gravida quam, vitae rutrum risus volutpat id. Donec a sapien nisi. Nam eget gravida tortor.\n\nUt non velit sit amet erat aliquet mattis. Vivamus et justo diam. Integer elementum dui id gravida egestas. Nam a malesuada dolor, eget ornare nibh. Proin sed fermentum sapien. Fusce eu tellus quis neque ullamcorper lacinia. Vivamus accumsan dui ac mauris eleifend rutrum. Vestibulum luctus erat a faucibus dictum. Integer fringilla mauris vel dapibus tempus. Proin dictum viverra sapien, et vulputate mauris ullamcorper nec. Sed malesuada dui vitae neque dictum, in faucibus leo egestas.\n\nVestibulum eget leo id metus congue rhoncus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat nisi ut varius imperdiet. Fusce bibendum velit ligula, quis varius lorem porta mattis. Cras blandit facilisis nibh ut suscipit. Proin finibus sem in velit laoreet euismod. Vivamus tristique dui sit amet ipsum facilisis semper. Integer rutrum turpis maximus orci ultricies, a sagittis ex luctus. Phasellus convallis sem eros, nec volutpat nulla convallis ut. Fusce nisl lectus, tincidunt tincidunt maximus sed, euismod vel libero. Cras id consequat mi.\n\nNunc porta auctor dolor vitae euismod. Suspendisse tellus mi, fringilla sed dapibus et, tincidunt at purus. Donec dignissim leo et urna commodo posuere. Curabitur et turpis sodales sapien venenatis tincidunt. In luctus vitae massa ac condimentum. Vestibulum nec lobortis ipsum. Fusce quis egestas ex.\n\nNullam rhoncus a dui et hendrerit. Curabitur tristique dapibus mi, at cursus augue blandit ut. Morbi faucibus vulputate est, sit amet consectetur nulla maximus eu. Quisque vitae metus ornare, vestibulum urna vitae, vehicula enim. Vestibulum id velit blandit, viverra lacus efficitur, pulvinar elit. Suspendisse dignissim congue interdum. Nulla ornare mauris quis orci tincidunt viverra. Cras sit amet facilisis orci, a mollis ex. Proin nec ex sit amet dolor interdum volutpat sit amet eget ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus non magna nec massa placerat dapibus nec eget massa. Quisque condimentum maximus ante, id tempus nisi ullamcorper sed.\n\nAenean viverra consequat augue et molestie. Maecenas sodales ac lorem vel ornare. Ut pharetra erat neque, nec rutrum nibh lobortis ac. Pellentesque facilisis eu odio nec fermentum. Suspendisse finibus, ipsum vel blandit viverra, est enim luctus dolor, eget porttitor nulla est cursus leo. Aenean a libero vel ante elementum placerat sit amet in velit. Proin sit amet volutpat massa. In et lacinia ante. Phasellus quis malesuada mauris, eu sagittis nisl. Quisque auctor, sapien nec varius consequat, purus quam bibendum dolor, at laoreet erat urna in orci. Curabitur luctus justo ipsum, quis malesuada sem ultrices non. Sed vel sem cursus, sagittis dolor eu, convallis magna.\n\nPraesent vestibulum egestas est molestie tempus. Quisque sit amet velit non orci pellentesque pretium. Aenean nec felis rhoncus, gravida ante vel, euismod eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam cursus molestie dapibus. Praesent finibus odio ut diam sollicitudin imperdiet. Maecenas blandit a leo eu sagittis. Maecenas rhoncus leo ullamcorper, blandit mauris ac, euismod quam. Donec nec urna pulvinar, iaculis mi eget, pretium nibh. Quisque vitae interdum massa. Sed ultrices ligula et erat lacinia molestie. Fusce et tortor ultricies, condimentum sapien vel, dignissim ex. Nam interdum in odio ut laoreet. Integer convallis turpis vitae enim luctus, eget egestas sapien molestie. Proin et nisi fringilla, aliquet tortor eget, sagittis tortor.\n\nDonec volutpat enim sit amet faucibus semper. Vivamus ultricies nisl id dictum vulputate. Maecenas sagittis odio id urna ornare, sit amet convallis lectus aliquet. Vestibulum viverra semper est, non facilisis urna commodo bibendum. Aliquam vestibulum augue leo, et varius nisl pharetra et. Duis in mi magna. Aenean in urna non erat aliquam eleifend id non eros. Praesent accumsan vestibulum est, sed interdum quam iaculis id. Quisque sapien eros, accumsan ut nulla quis, posuere pellentesque quam. Suspendisse nec tellus dui.\n\nAenean sit amet porta nisi, nec tristique felis. Phasellus varius mattis ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer lacus ex, fermentum sed tortor vitae, placerat pellentesque mauris. Aliquam iaculis ligula dictum est vehicula, nec tincidunt metus feugiat. Nulla facilisi. Aenean neque leo, egestas nec nisl ut, suscipit malesuada diam. Aenean non tellus lacinia, blandit nisl et, pharetra nunc. Ut a condimentum dolor. Etiam quis dolor at sem elementum faucibus. Nam sit amet dolor lobortis, finibus mi non, tincidunt odio. Cras dignissim congue leo, suscipit malesuada metus placerat non.\n\nNullam ut volutpat tortor. Donec nisl ipsum, mollis eget enim vitae, ornare tincidunt libero. Quisque finibus metus id sodales imperdiet. Suspendisse potenti. Duis libero nulla, imperdiet sed lorem sit amet, ornare auctor dolor. Ut nec odio ac nulla blandit ullamcorper sit amet non sem. Maecenas ut arcu ligula.\n\nCras venenatis dolor libero, vel mattis turpis cursus sed. Etiam a orci euismod, sagittis nisl in, placerat diam. Aenean sagittis aliquam ante. Aenean vel augue tellus. Aliquam at elit non nisi sagittis accumsan eget nec sem. Proin sed pretium tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas laoreet urna a nunc ullamcorper, in efficitur mi sodales.\n\nNulla malesuada pharetra nulla ut blandit. Cras cursus, nunc eu ultricies venenatis, justo mauris viverra augue, vitae mattis tellus velit ac magna. Vestibulum non urna ut nisl dignissim suscipit ac id mauris. Curabitur ut libero aliquet, sodales est et, scelerisque nisl. Nulla vel consequat augue, nec ornare arcu. Donec porta magna eu mattis volutpat. Nulla tempor ligula eu sagittis pellentesque. Cras facilisis ut lectus vel lobortis. Phasellus id felis urna. Pellentesque augue eros, pulvinar eget orci vitae, tempus commodo lacus. Cras ultricies mi vel fringilla vulputate. Donec sollicitudin sem dolor, ac pretium orci sodales a.\n\nVestibulum dolor dolor, malesuada in commodo ac, lacinia ut mi. Fusce eget est sagittis, euismod purus at, bibendum erat. Etiam sollicitudin consequat odio sollicitudin laoreet. In quis rutrum dolor. Fusce semper libero vel enim dapibus egestas. Morbi id sodales justo, eget tincidunt ex. Nullam dolor dui, iaculis eget odio vitae, sagittis sodales sapien.\n\nDuis sapien dui, sagittis sed aliquet eu, venenatis eu urna. Mauris vitae ipsum fermentum, maximus nulla quis, cursus ex. Suspendisse at ligula a nibh varius rhoncus efficitur ut ex. Integer ipsum turpis, molestie quis nibh nec, aliquam malesuada sapien. Ut laoreet, sem vehicula ultrices pretium, justo erat gravida purus, vel blandit purus leo in tortor. Phasellus sed pulvinar turpis. Morbi tincidunt pellentesque lectus nec molestie.\n\nSed nec nulla sed erat tristique scelerisque. Suspendisse diam leo, volutpat eu dapibus vel, ultricies non neque. Nulla vel diam sem. In augue arcu, feugiat sit amet ante vel, pretium viverra neque. Aliquam erat volutpat. Nunc imperdiet libero erat, id aliquam nisl gravida in. Vestibulum lacinia ex nibh, et feugiat risus luctus in. Aliquam erat volutpat. Pellentesque vehicula quam et orci sollicitudin laoreet. ',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-23 07:01:23',
    updatedAt: '2023-10-23 07:01:23',
  },
  {
    blogId: '6bc5b772-e4d2-40d6-a489-fa8b9256a60a',
    title: 'Test signal',
    body: 'Hello this is blog',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 08:57:28',
    updatedAt: '2023-10-18 08:57:28',
  },
  {
    blogId: '75079132-7826-4b5d-a290-104b09fcbba0',
    title: 'Blog test edit',
    body: 'New blog test',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-20 02:13:14',
    updatedAt: '2023-10-27 06:08:10',
  },
  {
    blogId: '94a49dc7-8af1-47e9-b6e2-b4a5d8db5e40',
    title: 'The Impact of Artificial Intelligence on Healthcare',
    body: 'Artificial Intelligence (AI) is rapidly transforming the healthcare industry. This blog delves into the myriad ways AI is revolutionizing patient care, from diagnosing diseases more accurately to optimizing treatment plans. Discover the latest AI applications in healthcare and the potential benefits for patients and medical professionals.',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 04:52:18',
    updatedAt: '2023-10-18 04:52:18',
  },
  {
    blogId: 'a08631bc-fa71-4705-be12-8caa4dd9e669',
    title: 'Cybersecurity Threats in a Hyperconnected World',
    body: 'With increased connectivity comes increased vulnerability to cyber threats. This blog will examine the evolving landscape of cybersecurity threats, including ransomware, phishing attacks, and data breaches. It will also provide practical tips and best practices to protect your digital assets.',
    authorId: '3a7ac5c7-706e-4ad2-aa2f-bde4f1820ae2',
    createdAt: '2023-10-10 02:39:00',
    updatedAt: '2023-10-10 02:39:00',
  },
  {
    blogId: 'a241babd-7b20-4fe7-be89-5b3109a288b0',
    title:
      'Augmented Reality (AR) and Virtual Reality (VR): Shaping the Future of Entertainment',
    body: 'AR and VR are transforming how we experience entertainment and education. This blog will explore the latest developments in AR and VR technology, including immersive gaming experiences, virtual classrooms, and their potential to revolutionize various industries beyond entertainment.',
    authorId: 'f11a211e-0101-45c8-bc71-18d31e30685e',
    createdAt: '2023-10-10 02:42:19',
    updatedAt: '2023-10-10 02:42:19',
  },
  {
    blogId: 'b33fc6ce-0432-49ae-b647-76bc1713a588',
    title: 'Sustainable Fashion: Redefining Style and Responsibility',
    body: 'Sustainability is a growing concern in the fashion world, and this blog explores how the industry is evolving. Learn about eco-friendly materials, ethical fashion practices, and how consumers can make more sustainable choices without sacrificing style. Discover the impact of "fast fashion" and why it\'s time for a change.',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 04:52:31',
    updatedAt: '2023-10-18 04:52:31',
  },
  {
    blogId: 'bb2d11f2-b6c9-4cef-ace4-5376392ab2db',
    title: 'dfgbfgdfbdfbdfb',
    body: 'dfgbdfghfgn ty nrytrtryterytrtytrytrytrytrrytrytryt',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 11:39:42',
    updatedAt: '2023-10-18 11:39:42',
  },
  {
    blogId: 'c472b22e-0523-4aaf-90fb-c5601da76713',
    title: 'Test blog',
    body: 'This is test blog body',
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 11:07:22',
    updatedAt: '2023-10-18 11:07:22',
  },
  {
    blogId: 'd7e75e55-c412-4f59-9448-1c1a9b89d804',
    title: 'The Science of Procrastination: Why We Do It and How to Stop',
    body: "Procrastination is a common struggle, but what's the science behind this habit? This blog dives into the psychology of procrastination, the factors that lead to it, and practical strategies to overcome it. By understanding the roots of procrastination, you can increase your productivity and achieve your goals.",
    authorId: 'c50541ee-0e0d-4424-acf5-ad50b9b0c715',
    createdAt: '2023-10-18 04:52:54',
    updatedAt: '2023-10-18 04:52:54',
  },
  {
    blogId: 'dbc28b70-908e-4ec2-8155-e49352b52bce',
    title: 'test title',
    body: 'hello title',
    authorId: '3a7ac5c7-706e-4ad2-aa2f-bde4f1820ae2',
    createdAt: '2023-10-10 09:37:02',
    updatedAt: '2023-10-10 09:37:02',
  },
];

export default blogsData
